"""add prompt to text_coreection_history

Revision ID: 976a3afcfced
Revises: cca41145d8b0
Create Date: 2025-08-12 14:55:17.939076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '976a3afcfced'
down_revision: Union[str, None] = 'cca41145d8b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('text_correction_history', sa.Column('prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('text_correction_history', 'prompt')
    # ### end Alembic commands ###
