"""Add operation_type and language fields to TextCorrectionHistory

Revision ID: 35d66ba6638c
Revises: b6fa1de37562
Create Date: 2025-09-10 18:40:42.770602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35d66ba6638c'
down_revision: Union[str, None] = 'b6fa1de37562'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the ENUM type first
    operation_type_enum = sa.Enum('correction', 'translation', 'translation_correction', name='operationtype')
    operation_type_enum.create(op.get_bind())
    
    op.add_column('text_correction_history', sa.Column('operation_type', operation_type_enum, server_default='correction', nullable=False))
    op.add_column('text_correction_history', sa.Column('source_lang', sa.String(length=10), nullable=True))
    op.add_column('text_correction_history', sa.Column('target_lang', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_text_correction_history_operation_type'), 'text_correction_history', ['operation_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_text_correction_history_operation_type'), table_name='text_correction_history')
    op.drop_column('text_correction_history', 'target_lang')
    op.drop_column('text_correction_history', 'source_lang')
    op.drop_column('text_correction_history', 'operation_type')
    
    # Drop the ENUM type
    operation_type_enum = sa.Enum('correction', 'translation', 'translation_correction', name='operationtype')
    operation_type_enum.drop(op.get_bind())
    # ### end Alembic commands ###
