"""create prompt table

Revision ID: b6fa1de37562
Revises: 976a3afcfced
Create Date: 2025-08-12 19:21:50.471374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6fa1de37562'
down_revision: Union[str, None] = '976a3afcfced'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_prompts',
    sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
    sa.Column('category', sa.Enum('TITLE', 'BODY', 'CAPTION', name='article_prompts_category'), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.UniqueConstraint('category', name='uq_article_prompts_category')
    )
    op.create_index('ix_article_prompts_category', 'article_prompts', ['category'], unique=False)
    op.create_index(op.f('ix_article_prompts_id'), 'article_prompts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_article_prompts_id'), table_name='article_prompts')
    op.drop_index('ix_article_prompts_category', table_name='article_prompts')
    op.drop_table('article_prompts')
    # ### end Alembic commands ###
